create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  url text not null unique,
  description text,
  score integer,
  status text not null default 'new',
  applied_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  last_seen date not null default current_date
);

create index if not exists jobs_status_idx on public.jobs (status);
create index if not exists jobs_score_idx on public.jobs (score desc);

create table if not exists public.chat_history (
  id bigint generated by default as identity primary key,
  role text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vector_memory (
  id bigint generated by default as identity primary key,
  topic text not null,
  content text not null,
  embedding jsonb not null,
  created_at timestamptz not null default now()
);
